# Generated by Django 4.1.3 on 2022-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=2, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
