# Generated by Django 4.1.3 on 2022-11-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/user.png', null=True, upload_to='profiles'),
        ),
    ]
