# Generated by Django 4.1.3 on 2022-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_order_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
